### ISSUE TITLE
problem with realization? (проблема с путями)

### ISSUE THREAD

**Issue by hik200** [sankam-nikolya/yii2-kinopoisk-parser#1]
http://imgur.com/LTDYfM8

**Comment by sankam-nikolya** [comment]
устанавливали пакет через composer?

**Comment by hik200** [comment]
да

2016-07-24 8:02 GMT+03:00 Nikolya notifications@github.com:

**Comment by sankam-nikolya** [comment]
странно

тогда на строке 64 в файле kinopoisk.php нужно добавить:

```
if(!class_exists('Kpparser')) {
    require_once(__DIR__.'/kpparser.php');
}
```

**Comment by sankam-nikolya** [comment]
странно

для на чала попробуйте изменить строку 65 в файле  kinopoisk.php на

`$parser =  new sankam\parser\Kpparser($options);`

если результата не будет, тогда на строке 64 в файле kinopoisk.php нужно добавить:

`
if(!class_exists('Kpparser')) {
    require_once(__DIR__.'/kpparser.php');
}
`
